local ErrorType = {
    ADDRESS_MISSING = "ADDRESS_MISSING",
    ADDRESS_INVALID = "ADDRESS_INVALID",
    ADDRESS_INCOMPLETE = "ADDRESS_INCOMPLETE",
    OUT_OF_RANGE = "OUT_OF_RANGE",
    ADDRESS_TOO_LONG = "ADDRESS_TOO_LONG",
}

return ErrorType